module.exports = [
  {
    _id: "1",
    name: "Nutty Hazelnut",
    category: "Instant Coffee",
    img: "/images/product_images/instant-coffee-product-card.webp",
    discount: "10",
    price: "500",
    inStock: true,
    rating: "4.3",
  },
  {
    _id: "2",
    name: "Berry Blast",
    category: "Instant Coffee",
    img: "/images/product_images/instant-coffee-product-card.webp",
    discount: "10",
    price: "500",
    inStock: true,
    rating: "3.3",
  },
  {
    _id: "3",
    name: "Classic Gold",
    category: "Instant Coffee",
    img: "/images/product_images/instant-coffee-product-card.webp",
    discount: "0",
    price: "700",
    inStock: false,
    rating: "4.8",
  },
  {
    _id: "4",
    name: "Classic Brew Gold",
    category: "Ground Coffee",
    img: "/images/product_images/instant-coffee-product-card.webp",
    discount: "15",
    price: "1000",
    inStock: true,
    rating: "2.0",
  },
  {
    _id: "5",
    name: "Hazelnut Delight",
    category: "Ground Coffee",
    img: "/images/product_images/instant-coffee-product-card.webp",
    discount: "5",
    price: "1200",
    inStock: false,
    rating: "4.9",
  },
  {
    _id: "6",
    name: "Very Berry",
    category: "Ground Coffee",
    img: "/images/product_images/instant-coffee-product-card.webp",
    discount: "15",
    price: "1350",
    inStock: true,
    rating: "3.0",
  },
];
